CREATE TABLE IF NOT EXISTS `monitoring_errors` (
 `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 `method` VARCHAR(16) NOT NULL,
 `route` VARCHAR(255) NOT NULL,
 `status` INT NOT NULL
);
