CREATE TABLE IF NOT EXISTS activity_logs (
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
user_name VARCHAR(255) NOT NULL, role VARCHAR(30) NOT NULL,
module VARCHAR(40) NOT NULL, action VARCHAR(40) NOT NULL,
description VARCHAR(500) NOT NULL, status VARCHAR(20) NOT NULL,
INDEX activity_logs_created_at_idx (created_at)
);
