import Image from 'next/image';
import Link from 'next/link';
import { Check } from 'lucide-react';

const benefits = [
  ['Cepat', 'Bandwidth stabil untuk bekerja, belajar, streaming, dan bermain game.'],
  ['Aman', 'Jaringan terkelola dengan pemantauan dan perawatan rutin.'],
  ['Responsif', 'Tim teknis siap membantu saat Anda membutuhkan dukungan.'],
];
const packages = [
  ['Fiber Pemula', '50.000', '10 Mbps', 'Untuk browsing, belajar, dan penggunaan harian.', false],
  ['Fiber Keluarga', '100.000', '20 Mbps', 'Nyaman untuk streaming, bekerja, dan banyak perangkat.', true],
  ['Fiber Usaha', '150.000', '30 Mbps', 'Koneksi andal untuk usaha dan kebutuhan lebih intensif.', false],
] as const;

export default function Home() {
  return <div className="bg-white text-slate-800">
    <nav className="fixed top-0 z-50 w-full border-b border-blue-100 bg-white/95 shadow-sm backdrop-blur-md">
      <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
        <a href="#beranda" className="flex items-center gap-3"><Image src="/logo.png" alt="Logo PT UNZANET" width={92} height={44} className="h-11 w-auto"/><span className="font-extrabold tracking-wide">PT UNZANET</span></a>
        <div className="hidden items-center gap-1 md:flex">{[['Beranda','beranda'],['Tentang Kami','tentang-kami'],['Layanan','layanan'],['Kontak','kontak']].map(([label,id]) => <a key={id} href={`#${id}`} className="rounded-lg px-4 py-2 text-sm font-medium text-slate-600 hover:bg-blue-50 hover:text-blue-700">{label}</a>)}<Link href="/login" className="ml-2 rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white">Login</Link></div>
      </div>
    </nav>
    <main className="pt-16">
      <section id="beranda" className="relative isolate flex min-h-[620px] items-center overflow-hidden bg-slate-950 text-white scroll-mt-16">
        <Image src="/landing-background.jpeg" fill priority alt="Jaringan fiber optik PT UNZANET" className="-z-20 object-fill"/><div className="absolute inset-0 -z-10 bg-gradient-to-r from-slate-950/95 via-slate-950/75 to-slate-950/20"/>
        <div className="mx-auto w-full max-w-7xl px-4 py-24 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="mb-5 text-sm font-semibold uppercase tracking-[.24em] text-cyan-300">Internet Fiber Optik Terpercaya</p><h1 className="mb-6 text-4xl font-bold leading-tight sm:text-5xl lg:text-6xl">Koneksi Internet Cepat & Stabil untuk Lingkungan Anda</h1><p className="mb-9 max-w-2xl text-lg leading-relaxed text-slate-200">PT UNZANET menyediakan layanan internet fiber optik berkualitas dengan harga terjangkau untuk kebutuhan rumah, komunitas, dan usaha Anda.</p><div className="flex flex-wrap gap-4"><a href="#layanan" className="rounded-lg bg-cyan-400 px-7 py-3.5 font-semibold text-slate-950 hover:bg-cyan-300">Lihat Paket</a><a href="#kontak" className="rounded-lg border border-white/50 bg-white/10 px-7 py-3.5 font-semibold backdrop-blur-sm hover:bg-white/20">Hubungi Kami</a></div></div></div>
      </section>
      <section id="tentang-kami" className="scroll-mt-16 py-20"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-[.9fr_1.1fr] lg:px-8"><div><p className="mb-3 text-sm font-semibold uppercase tracking-[.2em] text-blue-600">Tentang Kami</p><h2 className="mb-5 text-3xl font-bold sm:text-4xl">Internet berkualitas untuk koneksi tanpa batas</h2><p className="leading-relaxed text-slate-600">PT UNZANET menghadirkan jaringan fiber optik yang cepat, stabil, dan terjangkau. Infrastruktur modern serta dukungan teknis profesional kami siap menunjang aktivitas digital sehari-hari.</p></div><div className="grid gap-5 sm:grid-cols-3">{benefits.map(([title,desc]) => <article key={title} className="rounded-2xl border border-blue-100 bg-blue-50/70 p-6"><span className="mb-4 flex h-11 w-11 items-center justify-center rounded-xl bg-blue-700 text-white"><Check/></span><h3 className="mb-2 text-lg font-bold">{title}</h3><p className="text-sm leading-relaxed text-slate-600">{desc}</p></article>)}</div></div></section>
      <section id="layanan" className="scroll-mt-16 bg-blue-50 py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto mb-14 max-w-2xl text-center"><p className="mb-3 text-sm font-semibold uppercase tracking-[.2em] text-blue-600">Layanan</p><h2 className="mb-4 text-3xl font-bold sm:text-4xl">Paket transparan, tanpa biaya tersembunyi</h2><p className="text-slate-600">Pilih paket internet bulanan yang sesuai dengan kebutuhan Anda.</p></div><div className="mx-auto grid max-w-5xl gap-7 md:grid-cols-3">{packages.map(([name,price,speed,desc,popular]) => <article key={name} className={`relative flex flex-col rounded-2xl border bg-white p-7 shadow-sm ${popular?'border-blue-600 ring-2 ring-blue-600/10':'border-slate-200'}`}>{popular&&<span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-blue-700 px-4 py-1 text-xs font-bold uppercase tracking-wider text-white">Paling Populer</span>}<h3 className="text-xl font-bold">{name}</h3><p className="mt-2 min-h-12 text-sm text-slate-500">{desc}</p><div className="my-7"><span className="font-semibold">Rp </span><span className="text-4xl font-extrabold">{price}</span><span className="text-sm text-slate-500"> /bulan</span></div><dl className="mb-7 divide-y divide-slate-100 text-sm">{[['Kecepatan',speed],['Batas data','Tanpa batas'],['Dukungan','Teknis responsif']].map(([a,b])=><div key={a} className="flex justify-between py-3"><dt className="text-slate-500">{a}</dt><dd className="font-semibold">{b}</dd></div>)}</dl><a href="#kontak" className={`mt-auto rounded-lg px-5 py-3 text-center text-sm font-semibold ${popular?'bg-blue-700 text-white':'border border-slate-300'}`}>Pilih Paket</a></article>)}</div></div></section>
      <section id="kontak" className="scroll-mt-16 bg-slate-950 py-20 text-white"><div className="mx-auto grid max-w-7xl items-center gap-10 px-4 sm:px-6 lg:grid-cols-[1fr_auto] lg:px-8"><div><p className="mb-3 text-sm font-semibold uppercase tracking-[.2em] text-cyan-300">Kontak Kami</p><h2 className="mb-4 text-3xl font-bold sm:text-4xl">Siap menikmati internet yang lebih stabil?</h2><p className="max-w-2xl text-slate-300">Hubungi tim PT UNZANET untuk mengecek jangkauan, berkonsultasi, atau memilih paket yang paling sesuai.</p></div><div className="flex flex-col gap-3"><a href="https://wa.me/6281234567890" className="rounded-lg bg-cyan-400 px-7 py-3.5 text-center font-semibold text-slate-950">Chat WhatsApp</a><a href="mailto:info@unzanet.com" className="rounded-lg border border-slate-600 px-7 py-3.5 text-center font-semibold">Kirim Email</a></div></div></section>
    </main>
    <footer className="border-t border-slate-800 bg-slate-950 text-white"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-4 py-9 md:flex-row md:items-center md:justify-between"><div className="flex items-center gap-3"><Image src="/logo.png" alt="Logo" width={90} height={44}/><div><p className="font-bold">PT UNZANET</p><p className="text-sm text-slate-400">Internet fiber optik cepat dan stabil.</p></div></div><p className="text-sm text-slate-500">© {new Date().getFullYear()} PT UNZANET.</p></div></footer>
  </div>;
}
